ballerina-platform/module-ballerinax-postgresql

- gradle.properties
- postgresql-ballerina/Ballerina.toml
> Update the module version to 0.1.0-SNAPSHOT
> Update the module version to 0.1.0-SNAPSHOT

- .github/pull_request_template.md
- .github/workflows/build-master.yml
- .github/workflows/publish-release.yml
- changelog.md
> Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/1262
>Add changelog.
>Update pull_request_template.md content.
>Add new tokens iin Github Actions.
> Introduce a New Set of Credentials for Publishes and Changelog 

- postgresql-ballerina/tests/call-procedures-test.bal
- postgresql-ballerina/tests/execute-params-test.bal
- postgresql-ballerina/types.bal
- postgresql-native/src/main/java/org/ballerinalang/postgresql/utils/ConverterUtils.java
Add testcases for User defined types insertion operation
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/1278
> Add Testcases for User Defined type Insert Operation

- gradle.properties
> Upgrade the module version to beta.2

- postgresql-ballerina/Module.md
- postgresql-examples/atomic-batch-operation/README.md
- postgresql-examples/batch-operation/README.md
- postgresql-examples/call-stored-procedures/README.md
- postgresql-examples/complex-queries-operation/README.md
- postgresql-examples/execute-operation/README.md
- postgresql-examples/query-operation/README.md
Fix doc issue
Related issue:  [1537](https://github.com/ballerina-platform/ballerina-standard-library/issues/1537) & [1539](https://github.com/ballerina-platform/ballerina-standard-library/issues/1539)
> Fix doc issue

- gradle.properties
> Sync master after Release 0.7.0 beta.2

- gradle.properties
- native/src/main/java/io/ballerina/stdlib/postgresql/parameterprocessor/PostgresResultParameterProcessor.java
Migrates to latest SQL dependency
Depends on https://github.com/ballerina-platform/module-ballerina-sql/pull/311
> Improve abstraction of SQL native code

- ballerina/client.bal
- ballerina/tests/query-params-test.bal
- changelog.md
- gradle.properties
- native/src/main/java/io/ballerina/stdlib/postgresql/nativeimpl/QueryProcessorUtils.java
> Add support for query row

- gradle.properties
- native/src/main/java/io/ballerina/stdlib/postgresql/nativeimpl/CallProcessorUtils.java
- native/src/main/java/io/ballerina/stdlib/postgresql/nativeimpl/ExecuteProcessorUtils.java
- native/src/main/java/io/ballerina/stdlib/postgresql/nativeimpl/QueryProcessorUtils.java
> Migrate to latest SQL dependency

- gradle.properties
- native/src/main/java/io/ballerina/stdlib/postgresql/nativeimpl/ClientProcessorUtils.java
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/1808
> Add auto generated keys retrieval flags

- ballerina/tests/execute-basic-test.bal
- ballerina/tests/query-params-test.bal
- gradle.properties
- native/src/main/java/io/ballerina/stdlib/postgresql/parameterprocessor/PostgresResultParameterProcessor.java
- native/src/main/java/io/ballerina/stdlib/postgresql/parameterprocessor/PostgresStatementParameterProcessor.java
- native/src/main/java/io/ballerina/stdlib/postgresql/parameterprocessor/StatementParameterUtils.java
- native/src/main/java/io/ballerina/stdlib/postgresql/utils/ConversionHelperUtils.java
- native/src/main/java/io/ballerina/stdlib/postgresql/utils/ConverterUtils.java
$subject. The changes come from SQL dependency
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/1807
> Improve error types

- README.md
- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- ballerina/client.bal
- ballerina/tests/batch-execute-query-test.bal
- ballerina/tests/query-params-test.bal
- gradle.properties
- native/src/main/java/io/ballerina/stdlib/postgresql/nativeimpl/QueryProcessorUtils.java
$subject due to SQL module change https://github.com/ballerina-platform/module-ballerina-sql/pull/376
Fixes:
> Remove string usages from queryRow and batchUpdate

- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/trivy-scan.yml
- README.md
- ballerina/build.gradle
- examples/build.gradle
$Subject
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/1849
> Integrate Trivy vulnerability scanner

- README.md
- ballerina/Module.md
$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/1914
Similar PR: https://github.com/ballerina-platform/module-ballerina-sql/pull/379
> Update module.md with queryRow() documentation

- ballerina/Module.md
- ballerina/client.bal
- ballerina/tests/call-procedures-test.bal
- ballerina/tests/execute-basic-test.bal
- ballerina/tests/query-params-test.bal
- examples/atomic-batch-operation/atomic_batch_operation.bal
- examples/batch-operation/batch_operation.bal
$Subject 
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/1880
> Remove string usages in queries

- ballerina/Module.md
- ballerina/client.bal
> Improve module.md content

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- ballerina/client.bal
- ballerina/tests/call-procedures-test.bal
- ballerina/tests/connection-init-test.bal
- changelog.md
- gradle.properties
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2390
To be merged after: https://github.com/ballerina-platform/module-ballerina-sql/pull/441
> Change queryRow() API accept anydata as the return-type instead of any

- ballerina/procedure_params.bal
- changelog.md
- gradle.properties
- native/src/main/java/io/ballerina/stdlib/postgresql/nativeimpl/OutParameterProcessorUtils.java
$subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/2388
N/A
> Update to latest OutParameterProcessorUtils change

- gradle.properties
$Subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2396
> Update gradle plugin  version

- load-tests/stored_procedures/src/stored_procedures.bal
$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2271
> Fix stored procedure load test

- ballerina/client.bal
- ballerina/procedure_params.bal
- ballerina/record_types.bal
- ballerina/tests/batch-execute-query-test.bal
- ballerina/tests/call-procedures-test.bal
- ballerina/tests/connection-init-test.bal
- ballerina/tests/connection-pool-test.bal
- ballerina/tests/connection-ssl-test.bal
- ballerina/tests/error.bal
- ballerina/tests/execute-basic-test.bal
- ballerina/tests/execute-params-test.bal
- ballerina/tests/function-test.bal
- ballerina/tests/query-complex-test.bal
- ballerina/tests/query-params-test.bal
- ballerina/tests/utils.bal
- ballerina/types.bal
- examples/atomic-batch-operation/atomic_batch_operation.bal
- examples/batch-operation/batch_operation.bal
- examples/call-stored-procedures/stored_procedures.bal
- examples/complex-queries-operation/complex_queries.bal
- examples/execute-operation/execute_operation.bal
- examples/query-operation/query_operation.bal
$subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2276
N/A
> Refactor code by removing anti patterns

- ballerina/client.bal
- ballerina/procedure_params.bal
- ballerina/types.bal
$subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2286
N/A
> Improve API docs

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- examples/atomic-batch-operation/atomic_batch_operation.bal
- examples/batch-operation/batch_operation.bal
- examples/call-stored-procedures/stored_procedures.bal
- examples/complex-queries-operation/complex_queries.bal
- examples/query-operation/query_operation.bal
$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2592
> Use query syntax instead of foreach

- .github/workflows/trigger-load-tests.yml
> Fix workflow payload

- .github/workflows/central-publish.yml
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2564
> Add workflow to push package to Ballerina Central Environments 

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- changelog.md
- gradle.properties
> Move to next minor version

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- gradle.properties
$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2885
> Update SQL dependency to latest timestamped version

- gradle.properties
> Update driver version

- gradle.properties
> Update Ballerina lang version to 2201.1.0-rc1.13

- gradle.properties
> Update to latest dependency version

- gradle.properties
> Update changelog with release 1.4.0

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- changelog.md
- gradle.properties
> Update SQL version

- .github/workflows/build-timestamped-master.yml
- .github/workflows/central-publish.yml
- .github/workflows/daily-build.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trivy-scan.yml
- README.md
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3027
> Move current AdoptOpenJDK to Adoptiu

- ballerina/Ballerina.toml
- build.gradle
- gradle.properties
> Add constraint dependency

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- ballerina/tests/call-procedures-test.bal
- ballerina/tests/query-complex-test.bal
- examples/atomic-batch-operation/Ballerina.toml
- examples/batch-operation/Ballerina.toml
- examples/call-stored-procedures/Ballerina.toml
- examples/complex-queries-operation/Ballerina.toml
- examples/execute-operation/Ballerina.toml
- examples/query-operation/Ballerina.toml
> Fix test failures

- ballerina/tests/call-procedures-test.bal
> Add test config

- README.md
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/Package.md
- build-config/resources/Ballerina.toml
- changelog.md
- docs/spec/spec.md
- gradle.properties
$Subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/3463
> Update slack links and versions

- gradle.properties
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/3463
> Update dependencies for SL update 3

- .github/workflows/build-timestamped-master.yml
> Ignore load tests changes for build

- gradle.properties
> Update to postgresql driver 42.4.3

- README.md
- ballerina/Module.md
- ballerina/Package.md
- changelog.md
$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/3710
> Improve API docs on postgresql.driver usages

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- changelog.md
- gradle.properties
$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/3763
> Enable non-Hikari logs

- .github/workflows/pull-request.yml
- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- gradle.properties
> Update sql version for type-reference support 

- .github/workflows/build-with-bal-test-native.yml
> Enable GraalVM check daily

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- gradle.properties
> Update to latest stdlib dependencies

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- changelog.md
- compiler-plugin-tests/build.gradle
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/postgresql/compiler/CompilerPluginTest.java
- compiler-plugin-tests/src/test/resources/diagnostics/sample7/Ballerina.toml
- compiler-plugin-tests/src/test/resources/diagnostics/sample7/main.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/postgresql/compiler/analyzer/MethodAnalyzer.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/postgresql/compiler/analyzer/RemoteMethodAnalyzer.java
$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4054
> Fix compiler plugin failure when the diagnostic code is null

- .github/workflows/publish-release.yml
> Fix sync PR description

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- compiler-plugin-tests/build.gradle
- compiler-plugin/src/main/java/io/ballerina/stdlib/postgresql/compiler/Constants.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/postgresql/compiler/Utils.java
- gradle.properties
$subject
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/3119
N/A
> Enable code coverage for compiler plugin

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- native/src/main/java/io/ballerina/stdlib/postgresql/parameterprocessor/PostgresResultParameterProcessor.java
- native/src/main/java/io/ballerina/stdlib/postgresql/parameterprocessor/PostgresStatementParameterProcessor.java
This is to support the build for https://github.com/ballerina-platform/ballerina-standard-library/issues/4344
> Fix object getType() API usage

- .github/workflows/build-timestamped-master.yml
- .github/workflows/central-publish.yml
- .github/workflows/daily-build.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trivy-scan.yml
- README.md
- ballerina/Ballerina.toml
- ballerina/Module.md
- ballerina/Package.md
- build-config/checkstyle/build.gradle
- build-config/resources/Ballerina.toml
- build-config/spotbugs-exclude.xml
- compiler-plugin-tests/build.gradle
- compiler-plugin/build.gradle
- examples/atomic-batch-operation/README.md
- examples/batch-operation/README.md
- examples/build.gradle
- examples/call-stored-procedures/README.md
- examples/complex-queries-operation/README.md
- examples/execute-operation/README.md
- examples/query-operation/README.md
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- load-tests/execute_operation/src/Ballerina.toml
- load-tests/query_operation/src/Ballerina.toml
- load-tests/stored_procedures/src/Ballerina.toml
- native/build.gradle
> Migrate to Java 17

- .gitattributes
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/build.gradle
> Fix build issues

- .github/workflows/build-timestamped-master.yml
- .github/workflows/central-publish.yml
- .github/workflows/daily-build.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trivy-scan.yml
> Update Java version to 17.0.7 in workflows

- examples/atomic-batch-operation/Performing Atomic Batch Operations with PostgreSQL.md
- examples/batch-operation/Performing Batch Operations with PostgreSQL.md
- examples/call-stored-procedures/Calling Stored Procedures with PostgreSQL.md
- examples/complex-queries-operation/Performing Complex Queries with PostgreSQL.md
- examples/execute-operation/Executing Queries with PostgreSQL.md
- examples/query-operation/Performing Queries with PostgreSQL.md
> Update example README files

- .github/workflows/build-timestamped-master.yml
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
> Use latest postgresql driver version

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
> Bump minor version

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
To update Ballerina lang and dependency versions for update 9
> Update lang and dependency versions for update 9

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/build.gradle
- build-config/resources/Ballerina.toml
- build.gradle
- compiler-plugin-tests/build.gradle
- compiler-plugin/build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- native/build.gradle
- settings.gradle
> Update version for update 11

- ballerina/Ballerina.toml
- ballerina/tests/call-procedures-test.bal
- ballerina/tests/function-test.bal
- gradle.properties
> Update the SQL version and enable testcases

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
> Sync release PR

- ballerina/build.gradle
- build.gradle
- gradle.properties
> Prepare u11 release

- ballerina/tests/listener_tests.bal
- gradle.properties
> Fix test cases for dependency fix
